### PR TITLE
[#144254009] Adding change to build.gradle, see comments for more

### PR DESCRIPTION
**Pull request by hoangpham95**
- Added `productFlavors` in `build.gradle` for `main` and `vconly`
- Added `AndroidManifest.xml` for `vconly` with different package name and `gameId`
- Added `google-services.json` for `vconly` package (by added new project into Firebase with different package name)
- Created new package to match with product flavors.

### CODE REVIEW

**Comment by MattFoley** [comment]
What are the gradle commands to build the two different versions now? We'll follow this up with adding making the build job changes for each of these.

**Comment by hoangpham95** [comment]
According to my Android gradle console, it said
`[:app:generateVCOnlyDebugSources, :app:generateVCOnlyDebugAndroidTestSources, :app:prepareVCOnlyDebugUnitTestDependencies, :app:mockableAndroidJar]`

**Comment by MattFoley** [comment]
You're good to merge here, but work on the matching line to this for your new package:
```
./gradlew clean :app:assembleRelease :app:crashlyticsUploadDistributionRelease --stacktrace --info --debug
```

**Comment by MattFoley** [comment]
Should build your new app, then upload it to Crashlytics, the `--stacktrace --info --debug` are just for extra logging, and aren't automatically needed.

**Pull request merged**
